module.exports = {
        "lineNumbers": true,
        "matchBrackets": true,
	"mode": 55,
	"value": "console.log('Hello, world!');",
        "autofocus": true,
        "indentUnit": 8,
        "indentWithTabs": true,
        "smartIndent": true,
        "tabSize": 8,
        "lineSeparator": null,
        "specialChars": {},
        "electricChars": true,
        "inputStyle": "textarea",
        "spellcheck": false,
        "rtlMoveVisually": true,
        "wholeLineUpdateBefore": true,
        "theme": 19,
        "keyMap": "default",
        "extraKeys": null,
        "configureMouse": null,
        "lineWrapping": false,
        "gutters": [
                "CodeMirror-linenumbers"
        ],
        "fixedGutter": true,
        "coverGutterNextToScrollbar": false,
        "scrollbarStyle": "native",
        "firstLineNumber": 1,
        "showCursorWhenSelecting": false,
        "resetSelectionOnContextMenu": true,
        "lineWiseCopyCut": true,
        "pasteLinesPerSelection": true,
        "readOnly": false,
        "disableInput": false,
        "dragDrop": true,
        "allowDropFileTypes": null,
        "cursorBlinkRate": 530,
        "cursorScrollMargin": 0,
        "cursorHeight": 1,
        "singleCursorHeightPerLine": true,
        "workTime": 100,
        "workDelay": 100,
        "flattenSpans": true,
        "addModeClass": false,
        "pollInterval": 100,
        "undoDepth": 200,
        "historyEventDelay": 1250,
        "viewportMargin": 10,
        "maxHighlightLength": 10000,
        "moveInputWithCursor": true,
        "tabindex": null,
        "direction": "ltr",
        "hintOptions": null,
	"styleActiveLine": true
}
